export const stations = [
  { name: 'Wolverhampton', crs: 'WVH' },
  { name: 'London Waterloo', crs: 'WAT' },
  { name: 'Birmingham New Street', crs: 'BHM' },
  { name: 'Manchester Piccadilly', crs: 'MAN' },
  { name: 'Edinburgh', crs: 'EDB' },
  { name: 'Glasgow Central', crs: 'GLC' },
  { name: 'Liverpool Lime Street', crs: 'LIV' },
  { name: 'Leeds', crs: 'LDS' },
  { name: 'York', crs: 'YRK' },
  { name: 'Bristol Temple Meads', crs: 'BRI' },
  { name: 'Reading', crs: 'RDG' },
  { name: 'Brighton', crs: 'BTN' },
  { name: 'Southampton Central', crs: 'SOU' },
  { name: 'Cardiff Central', crs: 'CDF' },
  { name: 'Bournemouth', crs: 'BMH' },
  { name: 'Oxford', crs: 'OXF' },
  { name: 'Cambridge', crs: 'CBG' },
  { name: 'Nottingham', crs: 'NOT' },
  { name: 'Sheffield', crs: 'SHF' },
  { name: 'Leicester', crs: 'LEI' },
  { name: 'Norwich', crs: 'NRW' },
  { name: 'Exeter St Davids', crs: 'EXD' },
  { name: 'Newcastle', crs: 'NCL' },
  { name: 'Plymouth', crs: 'PLY' },
  { name: 'Swindon', crs: 'SWI' },
  { name: 'Milton Keynes Central', crs: 'MKC' },
  { name: 'Derby', crs: 'DBY' },
  { name: 'Hull', crs: 'HUL' },
  { name: 'Preston', crs: 'PRE' },
  { name: 'Chester', crs: 'CTR' },
  { name: 'Swansea', crs: 'SWA' },
  { name: 'Portsmouth Harbour', crs: 'PMH' },
  { name: 'Coventry', crs: 'COV' },
  { name: 'Bath Spa', crs: 'BTH' },
  { name: 'Peterborough', crs: 'PBO' },
  { name: 'Salisbury', crs: 'SAL' },
  { name: 'East Croydon', crs: 'ECR' },
  { name: 'Guildford', crs: 'GLD' },
  { name: 'Luton', crs: 'LTN' },
  { name: 'Stevenage', crs: 'SVG' },
  { name: 'Watford Junction', crs: 'WFJ' },
  { name: 'Cheltenham Spa', crs: 'CNM' },
  { name: 'Woking', crs: 'WOK' },
  { name: 'Banbury', crs: 'BAN' },
  { name: 'Tonbridge', crs: 'TON' },
  { name: 'St Albans City', crs: 'SAC' },
  { name: 'Sevenoaks', crs: 'SEV' },
  { name: 'Ashford International', crs: 'AFK' },
  { name: 'Maidstone East', crs: 'MDE' },
  { name: 'Dover Priory', crs: 'DVP' },
  { name: 'London Blackfriars', crs: 'BFR' },
  // Additional stations
  { name: 'London Paddington', crs: 'PAD' },
  { name: 'London Euston', crs: 'EUS' },
  { name: 'London King\'s Cross', crs: 'KGX' },
  { name: 'London Liverpool Street', crs: 'LST' },
  { name: 'London Victoria', crs: 'VIC' },
  { name: 'Glasgow Queen Street', crs: 'GLQ' },
  { name: 'St Pancras International', crs: 'STP' },
  { name: 'Birmingham International', crs: 'BHI' },
  { name: 'Manchester Victoria', crs: 'MCV' },
  { name: 'Luton Airport Parkway', crs: 'LTN' },
  { name: 'Gatwick Airport', crs: 'GTW' },
  { name: 'Heathrow Terminal 5', crs: 'HWV' },
  { name: 'Bristol Parkway', crs: 'BPW' },
  { name: 'Doncaster', crs: 'DON' },
  { name: 'Newport (South Wales)', crs: 'NWP' },
  { name: 'Aberdeen', crs: 'ABD' },
  { name: 'Inverness', crs: 'INV' },
  { name: 'Dundee', crs: 'DEE' },
  { name: 'Stirling', crs: 'STG' },
  { name: 'Paisley Gilmour Street', crs: 'PYG' },
  { name: 'Carlisle', crs: 'CAR' },
  { name: 'Crewe', crs: 'CRE' },
  { name: 'Stafford', crs: 'STA' },
  { name: 'Warrington Bank Quay', crs: 'WBQ' },
  { name: 'Middlesbrough', crs: 'MBR' },
  { name: 'Darlington', crs: 'DAR' },
  { name: 'Chesterfield', crs: 'CHD' },
  { name: 'Wakefield Westgate', crs: 'WKF' },
  { name: 'Huddersfield', crs: 'HUD' },
  { name: 'Blackpool North', crs: 'BPN' },
  { name: 'Shrewsbury', crs: 'SHR' },
  { name: 'Hereford', crs: 'HFD' },
  { name: 'Colchester', crs: 'COL' },
  { name: 'Ipswich', crs: 'IPS' },
  { name: 'Basingstoke', crs: 'BSK' },
  { name: 'Farnborough', crs: 'FNB' },
  { name: 'Didcot Parkway', crs: 'DID' },
  { name: 'High Wycombe', crs: 'HWY' },
  { name: 'Slough', crs: 'SLO' },
  { name: 'Barking', crs: 'BKG' },
  { name: 'Romford', crs: 'RMF' },
  { name: 'West Croydon', crs: 'WCY' },
  { name: 'Orpington', crs: 'ORP' },
  { name: 'Folkestone Central', crs: 'FKC' },
  { name: 'Margate', crs: 'MAR' },
  { name: 'Canterbury West', crs: 'CBW' },
  { name: 'Whitstable', crs: 'WHI' },
];
